name: Test Docker Build

on: [workflow_dispatch]

jobs:
  test1:
    runs-on: [self-hosted, Linux, ARM64]

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: "1.21"
          cache: true
          
      - name: Build Sling
        run: bash scripts/build.sh

      - name: Build Docker
        run: |
          docker build -f cmd/sling/Dockerfile.arm64 -t slingdata/sling:dev-arm64 . 